# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 14:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False, verbose_name='ISBN')),
                ('title', models.CharField(max_length=191, verbose_name='タイトル')),
                ('sub_title', models.CharField(blank=True, max_length=191, verbose_name='サブタイトル')),
                ('series_name', models.CharField(blank=True, max_length=191, verbose_name='シリーズ名')),
                ('author', models.CharField(blank=True, max_length=191, verbose_name='著者')),
                ('publisher', models.CharField(blank=True, max_length=191, verbose_name='出版社')),
                ('book_size', models.CharField(blank=True, max_length=191, verbose_name='本サイズ')),
                ('publication_date', models.DateField(null=True, verbose_name='刊行日')),
                ('small_image_url', models.URLField(blank=True, verbose_name='サムネイルURL')),
                ('medium_image_url', models.URLField(blank=True, verbose_name='画像URL(中)')),
                ('large_image_url', models.URLField(blank=True, verbose_name='画像URL(大)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=191, verbose_name='タイトル')),
                ('body', models.TextField(blank=True, verbose_name='本文')),
                ('rating', models.IntegerField(blank=True, verbose_name='評価')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BookInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('borrow', '貸出'), ('return', '返却'), ('renewal', '延長'), ('purchase_request', '購入希望')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='MyBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_date', models.DateField(default=django.utils.timezone.now, verbose_name='購入日')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('optional_state', models.CharField(choices=[('available', '貸出可'), ('reference_only', '禁帯出'), ('lost', '紛失'), ('breakage', '破損'), ('unpurchased', '未購入')], default='available', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BookInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191, verbose_name='組織名')),
                ('id_slug', models.CharField(max_length=191, verbose_name='短縮名')),
                ('opt_lending_period', models.IntegerField(default=14, verbose_name='貸出期間(日)')),
                ('opt_max_renewal', models.IntegerField(default=2, verbose_name='最大延長可能回数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=32)),
                ('invite_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('invite_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mybook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.MyBook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(related_name='org_memberships', through='core.OrganizationMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mybook',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='event',
            name='mybook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.MyBook'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmember',
            unique_together=set([('organization', 'user'), ('organization', 'invite_email')]),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([('user', 'organization', 'book')]),
        ),
    ]
