# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 07:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinfo',
            options={'verbose_name': '書籍情報', 'verbose_name_plural': '書籍情報'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': '組織', 'verbose_name_plural': '組織'},
        ),
        migrations.AlterModelOptions(
            name='organizationmember',
            options={'verbose_name': '組織メンバー', 'verbose_name_plural': '組織メンバー'},
        ),
        migrations.AlterField(
            model_name='mybook',
            name='buy_date',
            field=models.DateField(default=datetime.date.today, verbose_name='購入日'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id_slug',
            field=models.CharField(db_index=True, help_text='URLに利用されます。英数とハイフンのみ。 例:gotolab', max_length=191, unique=True, verbose_name='短縮名'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='例:後藤研究室', max_length=191, verbose_name='組織名'),
        ),
    ]
